### PR TITLE
Update To 1.21

### PR DESCRIPTION
**Pull request by GrinlexGH**
IMPORTANT (or not) TODO:
fix
```
\nvidium\src\main\java\me\cortex\nvidium\mixin\minecraft\MixinWindow.java:26: warning: Unable to locate method mapping for @At(INVOKE_ASSIGN.<target>) 'Lorg/lwjgl/opengl/GL;createCapabilities()Lorg/lwjgl/opengl/GLCapabilities;'
    @Inject(method = "<init>", at = @At(value = "INVOKE_ASSIGN", target = "Lorg/lwjgl/opengl/GL;createCapabilities()Lorg/lwjgl/opengl/GLCapabilities;"))
    ^
```
It warns but it works so idk what I should do with it

### CODE REVIEW

**Comment by Earthcomputer** [comment]
Welcome to Minecraft modding. Do you have the Minecraft Development IntelliJ plugin? It should explain the issues you had with your mixins and supply quick fixes.

**Comment by GrinlexGH** [comment]
Yes, I have.
image

**Comment by GrinlexGH** [comment]
Wow, this warning disappeared when I restarted Idea.
But there is one more little issue. method headInit in MixinWindow causes Minecraft to crash, so I had to commented it. Anyway, it didn't do anything, so it's not an issue, but still...

**Comment by Earthcomputer** [comment]
The `Window` constructor has an implicit superconstructor call to `Object`. If you inject before a superconstructor call, your injector needs to be `static`, because `this` is uninitialized. However I believe `Inject` is not allowed before the superconstructor call. Maybe instead you could inject at `Object.<init>` with `shift = AFTER`.

**Comment by GrinlexGH** [comment]
if you meant this `@Inject(method = "<init>", at = @At(value = "HEAD", shift= At.Shift.AFTER))
private void headInit`, then it does not work

**Comment by Earthcomputer** [comment]
No, I meant injecting after `Object.<init>`, forget the `HEAD`.

**Comment by GrinlexGH** [comment]
Im a little bit dumb😭😭 could you write a right code pls? Like what you mean saying injecting after `Object.<init>`? Set `At`'s `value` to `Object.<init>`? It doesn't work. I tried googling this but found absolutely nothing

**Comment by Earthcomputer** [comment]
`@Inject(method = "<init>", at = @At(value = "INVOKE", target = "Ljava/lang/Object;<init>()V", shift = At.Shift.AFTER))`

**Comment by GrinlexGH** [comment]
oh it works

**Comment by KeiBoogie** [comment]
> oh it works

Can u publish?

**Comment by DuncanRuns** [comment]
> > oh it works
> 
> Can u publish?

https://github.com/GrinlexGH/nvidium/releases

Note to self, check fork releases before cloning and building 💀

**Comment by Earthcomputer** [comment]
Some people have tried this out and are getting the following error:
```
[18:39:16] [Thread-22/INFO]: OpenGL debug message: id=0, source=API, type=ERROR, severity=HIGH, message='Unknown internal debug message. The NVIDIA OpenGL driver has encountered
an out of memory error. This application might
behave inconsistently and fail.
(stop logging every single event of this type
because there are too many)
(pid=16112 javaw.exe 64bit)'
[18:39:16] [Thread-22/INFO]: OpenGL debug message: id=1285, source=API, type=ERROR, severity=HIGH, message='GL_OUT_OF_MEMORY error generated. Failed to allocate memory for sparse storage page.'
```

**Comment by GrinlexGH** [comment]
what other mods did he use besides nvidium? what kind of video card does he have and how much memory does it have? have such cases happened before, not with my build?

**Pull request closed without merging**
